import {
  SchoolTenant,
  UserProfile,
  StudyResource,
  Assignment,
  Quiz,
  PreviousYearQuestion,
  Notice,
  CalendarEvent,
  ImportantLink,
} from '../types.ts';

export const INITIAL_SCHOOLS: SchoolTenant[] = [
  {
    id: 'school_apex',
    name: 'Apex International Academy',
    code: 'AIA-2026',
    logo: '🏛️',
    tagline: 'Excellence in Academics & Character',
    accentColor: '#4f46e5',
    plan: 'Enterprise',
    status: 'active',
    studentCount: 1240,
    teacherCount: 78,
    storageUsedGb: 142.6,
    storageLimitGb: 500,
    academicYear: '2026 – 2027',
    classesCount: 24,
    joinedDate: 'Jan 2024',
  },
  {
    id: 'school_oakridge',
    name: 'Oakridge STEM High School',
    code: 'OST-8840',
    logo: '🔬',
    tagline: 'Empowering Next-Gen Innovators',
    accentColor: '#0ea5e9',
    plan: 'Standard',
    status: 'active',
    studentCount: 890,
    teacherCount: 52,
    storageUsedGb: 88.4,
    storageLimitGb: 250,
    academicYear: '2026 – 2027',
    classesCount: 18,
    joinedDate: 'Aug 2024',
  },
  {
    id: 'school_beacon',
    name: 'Beacon Crest Grammar School',
    code: 'BCG-1102',
    logo: '📚',
    tagline: 'Tradition of Scholarly Distinction',
    accentColor: '#d97706',
    plan: 'Starter',
    status: 'active',
    studentCount: 460,
    teacherCount: 31,
    storageUsedGb: 34.2,
    storageLimitGb: 100,
    academicYear: '2026 – 2027',
    classesCount: 12,
    joinedDate: 'Feb 2025',
  },
];

export const INITIAL_USERS: Record<string, UserProfile> = {
  student: {
    id: 'usr_std_01',
    name: 'Aarav Patel',
    email: 'aarav.patel@apexacademy.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    schoolId: 'school_apex',
    grade: 'Grade 10',
    section: 'Section A',
    rollNumber: '10-A-42',
    subjects: ['Physics', 'Mathematics', 'Chemistry', 'Computer Science', 'English Literature'],
  },
  teacher: {
    id: 'usr_tch_01',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@apexacademy.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    schoolId: 'school_apex',
    department: 'Department of Physical Sciences',
    subjects: ['Physics', 'Science Laboratory'],
  },
  admin: {
    id: 'usr_adm_01',
    name: 'Marcus Sterling',
    email: 'principal.office@apexacademy.edu',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    schoolId: 'school_apex',
    department: 'Office of the Principal & Academic Affairs',
  },
  superadmin: {
    id: 'usr_sup_01',
    name: 'Elena Rostova',
    email: 'elena@academiahub.cloud',
    role: 'superadmin',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    schoolId: 'school_apex',
    department: 'AcademiaHub Global Platform Operations',
  },
};

export const INITIAL_STUDY_RESOURCES: StudyResource[] = [
  {
    id: 'res_01',
    schoolId: 'school_apex',
    title: 'Chapter 04: Classical Mechanics & Newton’s Laws of Motion',
    description: 'Comprehensive lecture handbook with free body diagrams, worked numerical problems, and laboratory derivation proofs.',
    subject: 'Physics',
    grade: 'Grade 10',
    chapter: 'Chapter 04: Dynamics',
    resourceType: 'pdf',
    fileSize: '4.8 MB',
    authorName: 'Dr. Sarah Jenkins',
    authorRole: 'Head of Physics',
    uploadDate: 'Sep 18, 2026',
    downloadCount: 342,
    tags: ['Newtonian Mechanics', 'Vectors', 'Force Equilibrium'],
    bookmarked: true,
  },
  {
    id: 'res_02',
    schoolId: 'school_apex',
    title: 'Electromagnetic Induction & Faraday’s Laws Presentation Deck',
    description: 'High-definition 42-slide presentation covering Lenz’s law, magnetic flux variations, and AC generator principles.',
    subject: 'Physics',
    grade: 'Grade 10',
    chapter: 'Chapter 07: Electromagnetism',
    resourceType: 'presentation',
    fileSize: '12.4 MB',
    authorName: 'Dr. Sarah Jenkins',
    authorRole: 'Head of Physics',
    uploadDate: 'Sep 21, 2026',
    downloadCount: 289,
    tags: ['Faraday', 'Flux', 'Magnetic Field'],
    bookmarked: false,
  },
  {
    id: 'res_03',
    schoolId: 'school_apex',
    title: 'Quadratic Equations & Complex Roots Practice Worksheet',
    description: '45 curated practice questions ranging from standard discriminant evaluations to advanced Olympiad-level word problems.',
    subject: 'Mathematics',
    grade: 'Grade 10',
    chapter: 'Chapter 03: Algebra',
    resourceType: 'worksheet',
    fileSize: '1.2 MB',
    authorName: 'Prof. David Vance',
    authorRole: 'Senior Math Faculty',
    uploadDate: 'Sep 15, 2026',
    downloadCount: 412,
    tags: ['Quadratic Formula', 'Parabolas', 'Discriminant'],
    bookmarked: true,
  },
  {
    id: 'res_04',
    schoolId: 'school_apex',
    title: 'Periodic Table Trends & Chemical Bonding Master Notes',
    description: 'Color-coded summary of electronegativity gradients, ionization potentials, and VSEPR molecular geometry shapes.',
    subject: 'Chemistry',
    grade: 'Grade 10',
    chapter: 'Chapter 02: Chemical Structure',
    resourceType: 'notes',
    fileSize: '3.1 MB',
    authorName: 'Dr. Anita Roy',
    authorRole: 'Chemistry Faculty',
    uploadDate: 'Sep 19, 2026',
    downloadCount: 198,
    tags: ['Periodic Table', 'Valency', 'VSEPR'],
  },
  {
    id: 'res_05',
    schoolId: 'school_apex',
    title: 'Object-Oriented Programming in Python 3.12: Classes & Inheritance',
    description: 'Full code walk-throughs demonstrating polymorphism, encapsulation, dunder methods, and clean exception handling patterns.',
    subject: 'Computer Science',
    grade: 'Grade 10',
    chapter: 'Chapter 05: OOP Fundamentals',
    resourceType: 'ebook',
    fileSize: '6.7 MB',
    authorName: 'Eng. Kevin Zhao',
    authorRole: 'CS Department Lead',
    uploadDate: 'Sep 10, 2026',
    downloadCount: 310,
    tags: ['Python', 'OOP', 'Inheritance'],
  },
  {
    id: 'res_06',
    schoolId: 'school_apex',
    title: 'Video Lecture: Optical Ray Diagrams & Lens Formula Derivation',
    description: '28-minute masterclass explaining sign conventions, focal lengths, magnification equations, and real vs virtual images.',
    subject: 'Physics',
    grade: 'Grade 10',
    chapter: 'Chapter 05: Ray Optics',
    resourceType: 'video',
    fileSize: '450 MB Stream',
    authorName: 'Dr. Sarah Jenkins',
    authorRole: 'Head of Physics',
    uploadDate: 'Sep 22, 2026',
    downloadCount: 520,
    tags: ['Optics', 'Ray Diagrams', 'Refraction'],
    externalUrl: 'https://youtube.com',
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg_01',
    schoolId: 'school_apex',
    title: 'Projectile Motion Lab Analysis & Simulation Report',
    subject: 'Physics',
    grade: 'Grade 10',
    chapter: 'Chapter 04: Dynamics',
    assignedBy: 'Dr. Sarah Jenkins',
    dueDate: '2026-09-28',
    maxMarks: 30,
    instructions: 'Calculate the theoretical maximum range at 45 degrees, record PhET simulator trajectories for 30°, 45°, and 60°, and submit your error analysis PDF.',
    attachmentName: 'Projectile_Lab_Manual_v2.pdf',
    totalSubmissions: 38,
    totalStudents: 42,
    studentStatus: 'pending',
  },
  {
    id: 'asg_02',
    schoolId: 'school_apex',
    title: 'Calculus Optimization Problems: Surface Area Minimization',
    subject: 'Mathematics',
    grade: 'Grade 10',
    chapter: 'Chapter 06: Applications of Derivatives',
    assignedBy: 'Prof. David Vance',
    dueDate: '2026-09-26',
    maxMarks: 25,
    instructions: 'Solve Problems 12 through 18 from page 142. All steps must show the second derivative test proof for local extrema.',
    attachmentName: 'Math_Calculus_Set_A.pdf',
    totalSubmissions: 41,
    totalStudents: 42,
    studentStatus: 'submitted',
    submittedAt: 'Sep 23, 2026 · 18:42',
    studentSubmissionFile: 'Aarav_Patel_Calculus_Opt_Final.pdf',
  },
  {
    id: 'asg_03',
    schoolId: 'school_apex',
    title: 'Stoichiometry & Yield Calculation in Industrial Haber Process',
    subject: 'Chemistry',
    grade: 'Grade 10',
    chapter: 'Chapter 04: Reaction Kinetics',
    assignedBy: 'Dr. Anita Roy',
    dueDate: '2026-09-18',
    maxMarks: 20,
    instructions: 'Submit balanced chemical equations with limiting reagent deductions and percentage yield breakdown under varying catalytic pressures.',
    totalSubmissions: 42,
    totalStudents: 42,
    studentStatus: 'graded',
    obtainedMarks: 19,
    submittedAt: 'Sep 17, 2026 · 14:10',
    studentSubmissionFile: 'Aarav_Patel_Haber_Process_Report.pdf',
    teacherFeedback: 'Outstanding precision in limiting reagent calculation. Clean notation on Le Chatelier equilibrium shifts.',
  },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: 'quiz_01',
    schoolId: 'school_apex',
    title: 'Physics Mid-Term Check: Kinematics & Energy Conservation',
    subject: 'Physics',
    grade: 'Grade 10',
    chapter: 'Chapters 1–4',
    timeLimitMinutes: 10,
    totalMarks: 20,
    dueDate: '2026-09-30',
    status: 'active',
    questions: [
      {
        id: 'q1',
        question: 'A projectile is launched with initial speed v at angle θ above the horizontal. At the highest point of its trajectory, what is its vertical velocity component?',
        options: ['v · cos(θ)', 'v · sin(θ)', 'Zero (0 m/s)', '9.8 m/s²'],
        correctAnswerIndex: 2,
        explanation: 'At the apex of a parabolic trajectory under uniform gravity, the instantaneous vertical velocity momentarily reaches zero before reversing direction.',
      },
      {
        id: 'q2',
        question: 'If the net work done on a particle is positive, what can be deduced about its kinetic energy according to the Work-Energy Theorem?',
        options: ['Kinetic energy decreases', 'Kinetic energy increases', 'Kinetic energy remains constant', 'Kinetic energy drops to zero'],
        correctAnswerIndex: 1,
        explanation: 'Work-Energy Theorem states W_net = ΔK. If W_net > 0, then ΔK > 0, meaning final kinetic energy exceeds initial kinetic energy.',
      },
      {
        id: 'q3',
        question: 'Two identical spheres of mass m collide head-on in a perfectly elastic collision. Sphere 1 is moving at speed u while Sphere 2 is initially at rest. What is the speed of Sphere 1 immediately after impact?',
        options: ['u / 2', 'u', 'Zero (0 m/s)', '2u'],
        correctAnswerIndex: 2,
        explanation: 'In a 1D elastic collision between equal masses with one target at rest, the colliding bodies completely exchange their velocities. Sphere 1 stops completely.',
      },
      {
        id: 'q4',
        question: 'What is the SI unit of gravitational potential energy?',
        options: ['Watt (W)', 'Newton (N)', 'Joule (J)', 'Pascal (Pa)'],
        correctAnswerIndex: 2,
        explanation: 'Energy in all standard physical forms, including gravitational potential energy, is measured in Joules (kg·m²/s²).',
      },
    ],
  },
  {
    id: 'quiz_02',
    schoolId: 'school_apex',
    title: 'Algebra II: Quadratic Roots & Graphing Parabolas',
    subject: 'Mathematics',
    grade: 'Grade 10',
    chapter: 'Chapter 03',
    timeLimitMinutes: 15,
    totalMarks: 15,
    dueDate: '2026-09-22',
    status: 'completed',
    studentScore: 14,
    studentAttemptedAt: 'Sep 21, 2026',
    questions: [
      {
        id: 'qm1',
        question: 'For quadratic ax² + bx + c = 0, what does a discriminant value of Δ < 0 indicate?',
        options: ['Two distinct real roots', 'One repeated real root', 'Two complex conjugate roots', 'Infinitely many roots'],
        correctAnswerIndex: 2,
        explanation: 'A negative discriminant inside the square root of the quadratic formula produces non-real imaginary conjugate roots.',
      },
    ],
  },
];

export const INITIAL_PYQS: PreviousYearQuestion[] = [
  {
    id: 'pyq_01',
    schoolId: 'school_apex',
    title: 'Grade 10 Physics Final Board Examination Paper (Series A)',
    grade: 'Grade 10',
    subject: 'Physics',
    examType: 'Final Board',
    year: 2025,
    fileSize: '3.4 MB',
    hasSolution: true,
    downloads: 1420,
    uploadedBy: 'Dr. Sarah Jenkins',
  },
  {
    id: 'pyq_02',
    schoolId: 'school_apex',
    title: 'Grade 10 Mathematics Mid-Term Assessment with Full Marking Rubric',
    grade: 'Grade 10',
    subject: 'Mathematics',
    examType: 'Mid-Term',
    year: 2025,
    fileSize: '2.8 MB',
    hasSolution: true,
    downloads: 1180,
    uploadedBy: 'Prof. David Vance',
  },
  {
    id: 'pyq_03',
    schoolId: 'school_apex',
    title: 'Grade 10 Chemistry Preliminary Mock Board Paper',
    grade: 'Grade 10',
    subject: 'Chemistry',
    examType: 'Preliminary',
    year: 2024,
    fileSize: '4.1 MB',
    hasSolution: true,
    downloads: 940,
    uploadedBy: 'Dr. Anita Roy',
  },
  {
    id: 'pyq_04',
    schoolId: 'school_apex',
    title: 'Grade 10 Computer Science Board Theory & Practical Code Solutions',
    grade: 'Grade 10',
    subject: 'Computer Science',
    examType: 'Final Board',
    year: 2024,
    fileSize: '1.9 MB',
    hasSolution: true,
    downloads: 875,
    uploadedBy: 'Eng. Kevin Zhao',
  },
  {
    id: 'pyq_05',
    schoolId: 'school_apex',
    title: 'Grade 10 Physics Comprehensive Mid-Term Assessment',
    grade: 'Grade 10',
    subject: 'Physics',
    examType: 'Mid-Term',
    year: 2023,
    fileSize: '3.0 MB',
    hasSolution: false,
    downloads: 650,
    uploadedBy: 'Dr. Sarah Jenkins',
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not_01',
    schoolId: 'school_apex',
    title: 'Academic Term II Mid-Semester Examination Timetable Announced',
    content: 'The official datesheet for Term II examinations has been ratified by the Academic Council. Examinations will commence from Monday, October 12, 2026. Students must verify their hall seating allocations via their student portal.',
    priority: 'urgent',
    targetAudience: 'All',
    publishDate: 'Sep 23, 2026',
    expiryDate: 'Oct 20, 2026',
    authorName: 'Marcus Sterling',
    authorRole: 'Principal',
    attachmentName: 'Official_Datesheet_Term_II_2026.pdf',
  },
  {
    id: 'not_02',
    schoolId: 'school_apex',
    title: 'Science & Robotics Innovation Fair 2026 Registrations Open',
    content: 'Students from Grades 9 through 12 are invited to submit experimental prototypes and research abstracts. Selected projects will be sponsored for the National Science Symposium.',
    priority: 'important',
    targetAudience: 'Students',
    publishDate: 'Sep 20, 2026',
    expiryDate: 'Oct 05, 2026',
    authorName: 'Dr. Sarah Jenkins',
    authorRole: 'Head of Physics',
    attachmentName: 'Science_Fair_Guidelines_2026.pdf',
  },
  {
    id: 'not_03',
    schoolId: 'school_apex',
    title: 'Departmental Faculty Meeting: Term Curriculum Progress Audit',
    content: 'All faculty members are requested to assemble in Conference Hall B on Friday at 15:30 to review syllabus completion rates and formative assessment records.',
    priority: 'normal',
    targetAudience: 'Teachers',
    publishDate: 'Sep 22, 2026',
    expiryDate: 'Sep 26, 2026',
    authorName: 'Academic Affairs',
    authorRole: 'Dean Office',
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'evt_01',
    schoolId: 'school_apex',
    title: 'Physics Mid-Term Check Quiz Closes',
    category: 'quiz',
    date: '2026-09-30',
    time: '23:59',
    description: 'Online submission cutoff for Physics Kinematics 20-mark quiz.',
    targetGrade: 'Grade 10',
  },
  {
    id: 'evt_02',
    schoolId: 'school_apex',
    title: 'Calculus Assignment Due Date',
    category: 'assignment',
    date: '2026-09-26',
    time: '18:00',
    description: 'Optimization derivatives assignment submission deadline.',
    targetGrade: 'Grade 10',
  },
  {
    id: 'evt_03',
    schoolId: 'school_apex',
    title: 'Physics Projectile Motion Lab Deadline',
    category: 'assignment',
    date: '2026-09-28',
    time: '17:00',
    description: 'Upload simulation lab report with calculations.',
    targetGrade: 'Grade 10',
  },
  {
    id: 'evt_04',
    schoolId: 'school_apex',
    title: 'Term II Board Preparatory Examination Starts',
    category: 'exam',
    date: '2026-10-12',
    time: '09:00',
    description: 'Mid-term written examinations across all academic departments.',
    targetGrade: 'All Grades',
  },
  {
    id: 'evt_05',
    schoolId: 'school_apex',
    title: 'Autumn Scholastic Break (Campus Closed)',
    category: 'holiday',
    date: '2026-10-24',
    description: 'Official academic holiday for faculty and students.',
  },
  {
    id: 'evt_06',
    schoolId: 'school_apex',
    title: 'Annual STEM & Robotics Exhibition',
    category: 'event',
    date: '2026-10-18',
    time: '10:00',
    description: 'Campus auditorium exhibition open to parents and visiting delegates.',
  },
];

export const INITIAL_IMPORTANT_LINKS: ImportantLink[] = [
  {
    id: 'lnk_01',
    schoolId: 'school_apex',
    title: 'PhET Interactive Simulations for Science & Math',
    category: 'Virtual Labs',
    targetGrade: 'Grades 9–12',
    url: 'https://phet.colorado.edu',
    description: 'Interactive HTML5 research-based simulations for physics projectiles, circuits, molecular shapes, and quantum mechanics.',
  },
  {
    id: 'lnk_02',
    schoolId: 'school_apex',
    title: 'Desmos Advanced Graphing Calculator & Geometry',
    category: 'Mathematics',
    targetGrade: 'Grades 9–12',
    url: 'https://desmos.com',
    description: 'Fast, browser-based dynamic function plotter, parametric curve visualizer, and calculus tangent line explorer.',
  },
  {
    id: 'lnk_03',
    schoolId: 'school_apex',
    title: 'OpenStax Peer-Reviewed College & AP Textbooks',
    category: 'Digital Library',
    targetGrade: 'Grades 10–12',
    url: 'https://openstax.org',
    description: 'Free, openly licensed digital textbooks in University Physics, Organic Chemistry, and Calculus.',
  },
  {
    id: 'lnk_04',
    schoolId: 'school_apex',
    title: 'JSTOR Secondary Schools Academic Research Database',
    category: 'Research',
    targetGrade: 'Grades 11–12',
    url: 'https://jstor.org',
    description: 'Peer-reviewed scholarly literature, historical archives, and academic journals for high school thesis research.',
  },
  {
    id: 'lnk_05',
    schoolId: 'school_apex',
    title: 'Wolfram Alpha Computational Intelligence Engine',
    category: 'Tools',
    targetGrade: 'Grades 10–12',
    url: 'https://wolframalpha.com',
    description: 'Step-by-step mathematical problem solver, molecular formula balance, and physical constant reference.',
  },
];

export const MOCK_STUDENT_ROSTER = [
  { id: 'std_01', name: 'Aarav Patel', rollNo: '10-A-42', grade: 'Grade 10', section: 'A', email: 'aarav.patel@apexacademy.edu', attendance: '98%', status: 'Active', gpa: '3.92' },
  { id: 'std_02', name: 'Maya Lin', rollNo: '10-A-07', grade: 'Grade 10', section: 'A', email: 'maya.lin@apexacademy.edu', attendance: '95%', status: 'Active', gpa: '3.88' },
  { id: 'std_03', name: 'Liam O’Connor', rollNo: '10-A-19', grade: 'Grade 10', section: 'A', email: 'liam.oc@apexacademy.edu', attendance: '92%', status: 'Active', gpa: '3.65' },
  { id: 'std_04', name: 'Sophia Chen', rollNo: '10-A-24', grade: 'Grade 10', section: 'A', email: 'sophia.c@apexacademy.edu', attendance: '99%', status: 'Active', gpa: '4.00' },
  { id: 'std_05', name: 'Zainab Al-Hassan', rollNo: '10-A-33', grade: 'Grade 10', section: 'A', email: 'zainab.h@apexacademy.edu', attendance: '96%', status: 'Active', gpa: '3.79' },
  { id: 'std_06', name: 'Lucas Rossi', rollNo: '10-A-15', grade: 'Grade 10', section: 'A', email: 'lucas.r@apexacademy.edu', attendance: '88%', status: 'Active', gpa: '3.42' },
];

export const MOCK_TEACHER_ROSTER = [
  { id: 'tch_01', name: 'Dr. Sarah Jenkins', department: 'Physical Sciences', subjects: ['Physics', 'Advanced Optics'], classes: ['10-A', '10-B', '12-A'], email: 'sarah.jenkins@apexacademy.edu', status: 'Active', resourcesCount: 38 },
  { id: 'tch_02', name: 'Prof. David Vance', department: 'Mathematics', subjects: ['Calculus', 'Algebra II'], classes: ['10-A', '11-B', '12-C'], email: 'david.vance@apexacademy.edu', status: 'Active', resourcesCount: 52 },
  { id: 'tch_03', name: 'Dr. Anita Roy', department: 'Chemical Sciences', subjects: ['Chemistry', 'Organic Lab'], classes: ['10-A', '11-A'], email: 'anita.roy@apexacademy.edu', status: 'Active', resourcesCount: 29 },
  { id: 'tch_04', name: 'Eng. Kevin Zhao', department: 'Computer Science', subjects: ['Python OOP', 'Web Architecture'], classes: ['10-A', '11-A', '12-A'], email: 'kevin.zhao@apexacademy.edu', status: 'Active', resourcesCount: 44 },
];
